### ISSUE TITLE
Script should exit if LiveMount status is FAILED

### ISSUE THREAD

**Issue by shamsway** [rubrikinc/PowerShell-Backup-Validation#1]
The logic should be changed so the script exits if LiveMount status is `FAILED`. While testing I had a situation where a live mount failed, but the script was stuck in a loop.

**Comment by jaapbrasser** [comment]
Thanks for the feedback shamsway, we are working on improvements in this repo!

**Comment by jaapbrasser** [comment]
Fixed in PR #5
