### ISSUE TITLE
Invoke-Build stops at GetConfig

### ISSUE THREAD

**Issue by mhoffmania** [rubrikinc/PowerShell-Backup-Validation#4]
**Expected Behavior**

Script should continue with build.

**Current Behavior**

Script stops after IdentityPath. 

**Failure Information (for bugs)**

Please help provide information about the failure if this is a bug.

* Use verbose outputs to capture any debug information.
```
PS C:\Users\Martin Hoffman\Desktop\Rubrik\Backup Validations> $Splat = @{
>>     File            = '.\.build.ps1'
>>     EnvironmentFile = '.\environment\TestEnv.json'
>>     ConfigFile      = '.\config\TestVM.json'
>>     IdentityPath    = '.\credential'
>>     }
>>
>> Invoke-Build @Splat -Result Result
ERROR: Cannot bind parameter 'Status'. Cannot convert value "GetConfig" to type "VMware.VimAutomation.Sdk.Types.V1.TaskState". Error: "Unable to match the identifier name GetConfig to a valid enumerator name. Specify one of the following enumerator names and try again:
Queued, Running, Success, Error, Unknown"
Build ABORTED C:\Users\Martin Hoffman\Desktop\Rubrik\Backup Validations\.build.ps1. 0 tasks, 1 errors, 0 warnings 00:00:01.1586066
C:\Users\Martin Hoffman\Documents\WindowsPowerShell\Modules\InvokeBuild\5.4.5\Invoke-Build.ps1 : Cannot bind parameter
'Status'. Cannot convert value "GetConfig" to type "VMware.VimAutomation.Sdk.Types.V1.TaskState". Error: "Unable to mat
ch the identifier name GetConfig to a valid enumerator name. Specify one of the following enumerator names and try agai
n:
Queued, Running, Success, Error, Unknown"
At line:8 char:1
+ Invoke-Build @Splat -Result Result
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Build.ps1], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Invoke-Build.ps1
```

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

* Started with a new build.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version of project.
* Version of dependencies.
Powershell - 5.1.17134.590
InvokeBuild - 5.4.5
Rubrik - 4.0.0.216
RubrikBackupValidation - 1.0.0.0
VMware.PowerCLI - 11.2.0.12483598
* Version of operating system.
Windows 10

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```

**Comment by chriswahl** [comment]
Thank you for submitting this issue. I've asked @jaapbrasser and @mwpreston to see if they can assist with investigating the root cause and providing any updates to the use case necessary to make this work properly for you.

**Comment by mhoffmania** [comment]
I appreciate that, thank you.

**Comment by jaapbrasser** [comment]
Thanks for the report, I will try and replicate the issue that you are experiencing. You can expect an update in the next 24 hours!

**Comment by jaapbrasser** [comment]
Hello @mhoffmania,

Did you make any changes to the .build.ps1 file?

Also could you attempt to run the same code in PowerShell Core, it is available [https://github.com/PowerShell/PowerShell/releases/download/v6.1.3/PowerShell-6.1.3-win-x64.msi](here), and let me know what the output is there?

**Comment by mhoffmania** [comment]
Hi

Sorry for a late response. I will try to rerun the build in Core.

**Comment by jaapbrasser** [comment]
Thanks @mhoffmania , I will await your results and we will take it from there!

**Comment by mhoffmania** [comment]
Hi @jaapbrasser! Once again, sorry for a late response. I have now tested the script with PowerShell Core and everything is working as expected. Thank you for your support.

Cheers!
/Martin

**Comment by jaapbrasser** [comment]
@mhoffmania Happy to hear that Martin! Happy scripting!
